# 数据库实体路径
dbEntityPackages = com.accountserver.entity

# 是否使用缓存
useCache = false

# 服务器监听端口
port=28080

# 开启账号监管模式
enableSupervisor = true

# redis key 前缀
redisKeyPrefix = ac

# 账号中心地址
ucAddress = https://dummy.apiuc.menaapp.net

# SDK 配置
appId = 1234567890
appKey = dummyKey

# IAP 配置
iapEncryptKey = EB246FFD5017C25F
iapEncryptIv = DA426B207036D7D7

# IAP 是否校验签名
iapVerifySign = false

# 注册设备数量
deviceNum = 5

# 注册IP数量限制
ipNum = 20

# 检查玩家国家码开关
checkCountry = true

# 针对中国玩家的白名单服务器ID列表
whiteSidList = 1,2,3,4,5

# 设备类型黑名单
blackDevice = Pixel 2

# 是否允许空设备信息
allowEmptyDevice = false

# IP白名单
whiteIpList= 127.0.0.1;192.168.1.1
