# 最大活动对象数
maxTotal = 64

# 最大空闲状态对象数
maxIdle = 32

# 最小空闲状态对象数
minIdle = 16

# 池内没有返回对象时，最大等待时间
maxWaitMillis = 10000

# 是否进行有效性检查
testOnBorrow = true

# 是否进行有效性检查
testOnReturn = true

# “空闲链接”检测线程，检测的周期，毫秒数。
timeBetweenEvictionRunsMillis = 30000

# 是否检测它的空闲超时
testWhileIdle = true

# 对于“空闲链接”检测线程而言，每次检测的链接资源的个数。
numTestsPerEvictionRun = 50

# 服务器的IP
host = 192.168.1.199

# 服务器的PORT
port = 6379

# 服务器的密码
password = pwd4redis

# 连接超时时间
timeout = 10000