# 数据库实体路径
dbEntityPackages = com.accountserver.entity

# 是否检查签名
checkSignature = false

# 是否使用缓存
useCache = false

# 开启账号监管模式
enableSupervisor = false

# 服务器监听端口
port=8080

# redis key 前缀
redisKeyPrefix = ac

# 账号中心地址
ucAddress = https://game.uc.com

# SDK 配置
appId = 1234567890
appKey = dummy_app_key

# IAP 配置
iapEncryptKey = EB246FFD5017C25F
iapEncryptIv = DA426B207036D7D7

# IAP 是否校验签名
iapVerifySign = false

# 检查玩家国家码开关
checkCountry = true

# 注册设备数量
deviceNum = 20

# 注册IP数量限制
ipNum = 30

# 是否允许空设备信息
allowEmptyDevice = true

# 设备类型黑名单
blackDevice = Pixel 2

# IP白名单
whiteIpList= 192.168.1.1,192.168.1.2

# 测试环境
testMode = true

# 本地登录验证(false就走login_verification_url地址去验证登录合法性)
local = true
login_verification_url = http://43.242.200.39:18888/public/login_guest.php
